### ISSUE TITLE
Implementation for pyAutomagic preprocessing 

### ISSUE THREAD

**Issue by rbechto2** [NeuroDataDesign/pyautomagic#18]
**Is your feature request related to a problem? Please describe.**
Currently, there is no coherent preprocessing pipeline fully implemented for pyAutomagic.

**Describe the solution you'd like**
Implementation of the preprocessing pipeline from Matlab's Automagic into a python version. The preprocessing includes the prep_pipeline that detects bad channels in the data set, next it uses performFilter to clean the data set, then pefromEOGRegression removes EOG artifact (if EOG data is included). Then uses robust principal component analysis (performRPCA) to remove any noise left in the data set. Afterward, figures are made of the data at various stages.

**Group**
@AamnaLawrence @Nick3151 @rbechto2

**Comment by adam2392** [comment]
Cool, so it’d be awesome to see this encapsulated into a class with the member functions for each of these sub functions and then a large fit() function that will just operate with some default parameters. 

Mne comparability will be desired. 

Unit tests on each sub function and the overall fit function will be desired. 

Everything else looks great. Submit a PR and request reviews whenever you have changes.
